### ISSUE TITLE
Issue with a checklist

### ISSUE THREAD

**Issue by samdoran** [samdoran/playground#3]
There is a HUGE problem to fix in this repo. It's so complicated we need sub tasks.

- [x] Fix thing one
- [ ] Do more fixes
- [ ] Fix that last gnarly thing

**Comment by samdoran** [comment]
To make a checklist, you use this Markdown syntax:

```
- [ ] Task 1
- [ ] Task 2
```
